app:
  name: "example"
  package-name: "example"
  title: "Hof Starter Kit"

  config:
    gaTracking: "UA-000000-23"

    oauth:
      google: false
      facebook: false
      linkedin: false
      github: false

  mode: live
