app:
  name: "hof-starter-app"

  # mode: live

  config:
    gaTracking: "UA-000000-23"

    oauth:
      google: true
      facebook: true
      linkedin: false
      github: false

    mailer:
      provider: mailgun
      sender: "support@hofstadter.io"

    multilang:
      picker: true
      languages:
        - short: en
          code: en-US
        - short: es
          code: es-ES


