app:
  name: "hof-starter-app"

  config:
    gaTracking: "UA-000000-23"

    oauth:
      google: false
      facebook: false
      linkedin: false
      github: true

    mailer:
      provider: mailgun
      sender: "support@hofstadter.io"

    multilang:
      picker: true
      languages:
        - short: en
          code: en-US
        - short: es
          code: es-ES


