app:
  name: "{{AppName}}"

  author: "Hofstadter <support@hofstadter.io>"
  license: "BSD 3-Clause"

  homepage: "https://docs.hofstadter.io"

  keywords:
    - "Hofstadter"
    - "Studios"
    - "HofStarterApp"
    - "hof-starter-app"

